# List of events to log, set to [] for none
events: [

]

# Whether to whitelist the 'events' list or blacklist instead
whitelist: true

prefix:
  # MiniMessage-styled text, for more informations see https://docs.advntr.dev/minimessage/format.html
  # and for preview https://webui.advntr.dev, sed for all kinds of plugin output except for event logging
  general: '<gray>[<gradient:#00F0A0:#00A0F0>EventLogger</gradient>]</gray> '
  # Plaintext, used for event logging, empty by default to fit wider event logs
  logging: ''

# <editor-fold desc="Visual representation of some formatting options" defaultstate="collapsed">

# Block(position=[109, 97, 5871], type=Material.BEDROCK, data=BlockData(data=minecraft:bedrock))
#      ^         ^       ^^    ^      ^                ^^                                      ^
#      |         |       |     |      |                |                                       |
#      |         |       |     |      |                - class.separator         class.postfix -
#      |         |       |     |      - field.separator
#      |         |       |     - array.postfix
#      |         |       - array.separator
#      |         - array.prefix
#      - class.prefix

# </editor-fold>

format:
  class:
    # If set to true, Bukkit classes implementations prefixed with 'Craft' will
    # have the prefix removed
    alterNames: true
    prefix: '('
    separator: ', '
    postfix: ')'
  array:
    prefix: '['
    separator: ', '
    postfix: ']'
  field:
    separator: '='
  # Border to draw about each event log, https://wikipedia.org/wiki/Box-drawing_characters is a great go-to
  border:
    top-left: '┏'
    top: '━'
    top-right: '┓'
    left: '┃'
    right: '┃'
    bottom-left: '┗'
    bottom: '━'
    bottom-right: '┛'
