name: EventLogger
version: '$version'
main: dev.matytyma.eventlogger.EventLogger
api-version: '$apiVersion'
load: STARTUP
author: matytyma
libraries: [
  $libraries
]
commands:
  eventlogger:
    description: Main command for EventLogger
    aliases: [ el ]
