name: EventLogger
version: '1.0-SNAPSHOT'
main: dev.matytyma.eventlogger.EventLogger
api-version: '1.20'
load: STARTUP
author: matytyma
commands:
  elreload:
    description: Reloads plugin configuration
    aliases: [ eventloggerreload ]
