name: EventLogger
version: '$version'
main: dev.matytyma.eventlogger.EventLogger
api-version: '$apiVersion'
load: STARTUP
author: matytyma
libraries: [
  org.jetbrains.kotlin:kotlin-stdlib:2.0.0
]
commands:
  eventlogger:
    description: Main command for EventLogger
    aliases: [ el ]
  eventloggerreload:
    description: Reloads plugin configuration
    aliases: [ elreload ]
